kind: HierarchyConfig
apiVersion: configmanagement.gke.io/v1
metadata:
  name: resourcequotas
spec:
  resources:
  - group: ""
    kinds: [ "ResourceQuota" ]
---
kind: Repo
apiVersion: configmanagement.gke.io/v1
metadata:
  name: repo
spec:
  version: "0.1.0"
