kind: RoleBinding
# Add RBAC escalation prevention
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator
  namespace: bookstore
subjects:
- kind: User
  name: jingfangliu@google.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: reposync-admin
  apiGroup: rbac.authorization.k8s.io
