apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  namespace: foo
#type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  extra: YmFyCg==
